module.exports.siteInfo = {
    "base_url": "https://agmarknet.gov.in/SearchCmmMkt.aspx",
    "url": "https://agmarknet.gov.in/SearchCmmMkt.aspx?Tx_Commodity=19&Tx_State=AP&Tx_District=0&Tx_Market=0&DateFrom=01-Dec-2020&DateTo=31-Dec-2020&Fr_Date=01-Dec-2020&To_Date=31-Dec-2020&Tx_Trend=1&Tx_CommodityHead=Banana&Tx_StateHead=Andhra+Pradesh&Tx_DistrictHead=--Select--&Tx_MarketHead=--Select--",
    "headers": {
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
        "Accept-Encoding": "gzip, deflate, br",
        "Accept-Language": "en-US,en;q=0.9",
        "Cache-Control": "no-cache",
        "Connection": "keep-alive",
        "Host": "agmarknet.gov.in",
        "Pragma": "no-cache",
        "Referer": "https://agmarknet.gov.in/SearchCmmMkt.aspx?Tx_Commodity=19&Tx_State=AP&Tx_District=0&Tx_Market=0&DateFrom=01-Dec-2020&DateTo=31-Dec-2020&Fr_Date=01-Dec-2020&To_Date=31-Dec-2020&Tx_Trend=1&Tx_CommodityHead=Banana&Tx_StateHead=Andhra+Pradesh&Tx_DistrictHead=--Select--&Tx_MarketHead=--Select--",
        "sec-ch-ua": "\"Google Chrome\";v=\"93\", \" Not;A Brand\";v=\"99\", \"Chromium\";v=\"93\"",
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": "\"macOS\"",
        "Sec-Fetch-Dest": "document",
        "Sec-Fetch-Mode": "navigate",
        "Sec-Fetch-Site": "same-origin",
        "Sec-Fetch-User": "?1",
        "Upgrade-Insecure-Requests": "1",
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.63 Safari/537.36"
    },
    "query_params": {
        "Tx_Commodity": "19",
        "Tx_State": "AP",
        "Tx_District": "0",
        "Tx_Market": "0",
        "DateFrom": "01-Dec-2020",
        "DateTo": "31-Dec-2020",
        "Fr_Date": "01-Dec-2020",
        "To_Date": "31-Dec-2020",
        "Tx_Trend": "1",
        "Tx_CommodityHead": "Banana",
        "Tx_StateHead": "Andhra Pradesh",
        "Tx_DistrictHead": "--Select--",
        "Tx_MarketHead": "--Select--"
    }
}

module.exports.cropsToCode = {
    "Ajwan": "137",
    "Alasande Gram": "281",
    "Almond(Badam)": "325",
    "Alsandikai": "166",
    "Amaranthus": "86",
    "Ambada Seed": "130",
    "Amla(Nelli Kai)": "355",
    "Amphophalus": "102",
    "Antawala": "209",
    "Anthorium": "379",
    "Apple": "17",
    "Apricot(Jardalu/Khumani)": "326",
    "Arecanut(Betelnut/Supari)": "140",
    "Arhar (Tur/Red Gram)(Whole)": "49",
    "Arhar Dal(Tur Dal)": "260",
    "Ashgourd": "83",
    "Astera": "232",
    "Avare Dal": "269",
    "Bajra(Pearl Millet/Cumbu)": "28",
    "Balekai": "274",
    "Bamboo": "204",
    "Banana": "19",
    "Banana - Green": "90",
    "Barley (Jau)": "29",
    "Bay leaf (Tejpatta)": "321",
    "Beans": "94",
    "Beaten Rice": "262",
    "Beetroot": "157",
    "Bengal Gram Dal (Chana Dal)": "263",
    "Bengal Gram(Gram)(Whole)": "6",
    "Ber(Zizyphus/Borehannu)": "357",
    "Betal Leaves": "143",
    "Betelnuts": "41",
    "Bhindi(Ladies Finger)": "85",
    "Big Gram": "113",
    "Binoula": "51",
    "Bitter gourd": "81",
    "Black Gram (Urd Beans)(Whole)": "8",
    "Black Gram Dal (Urd Dal)": "264",
    "Black pepper": "38",
    "BOP": "380",
    "Borehannu": "189",
    "Bottle gourd": "82",
    "Bran": "290",
    "Brinjal": "35",
    "Broken Rice": "293",
    "Broomstick(Flower Broom)": "320",
    "Bull": "214",
    "Bullar": "284",
    "Bunch Beans": "224",
    "Butter": "272",
    "Cabbage": "154",
    "Calf": "215",
    "Camel Hair": "354",
    "Cane": "205",
    "Capsicum": "164",
    "Cardamoms": "40",
    "Carnation": "375",
    "Carrot": "153",
    "Cashew Kernnel": "238",
    "Cashewnuts": "133",
    "Cashewnuts": "36",
    "Castor Oil": "270",
    "Castor Seed": "123",
    "Cauliflower": "34",
    "Chakotha": "188",
    "Chapparad Avare": "169",
    "Chennangi (Whole)": "241",
    "Chennangi Dal": "295",
    "Cherry": "328",
    "Chikoos(Sapota)": "71",
    "Chili Red": "26",
    "Chilly Capsicum": "88",
    "Chow Chow": "167",
    "Chrysanthemum": "402",
    "Chrysanthemum(Loose)": "231",
    "Cinamon(Dalchini)": "316",
    "Cloves": "105",
    "Cluster beans": "80",
    "Coca": "315",
    "Cock": "368",
    "Cocoa": "104",
    "Coconut": "138",
    "Coconut": "37",
    "Coconut Oil": "266",
    "Coconut Seed": "112",
    "Coffee": "45",
    "Colacasia": "318",
    "Copra": "129",
    "Coriander(Leaves)": "43",
    "Corriander seed": "108",
    "Cotton": "15",
    "Cotton Seed": "99",
    "Cow": "212",
    "Cowpea (Lobia/Karamani)": "92",
    "Cowpea(Veg)": "89",
    "Cucumbar(Kheera)": "159",
    "Cummin Seed(Jeera)": "42",
    "Custard Apple (Sharifa)": "352",
    "Daila(Chandni)": "382",
    "Dal (Avare)": "91",
    "Dalda": "273",
    "Delha": "410",
    "Dhaincha": "69",
    "Drumstick": "168",
    "Dry Chillies": "132",
    "Dry Fodder": "345",
    "Dry Grapes": "278",
    "Duck": "370",
    "Duster Beans": "163",
    "Egg": "367",
    "Egypian Clover(Barseem)": "361",
    "Elephant Yam (Suran)": "296",
    "Field Pea": "64",
    "Fig(Anjura/Anjeer)": "221",
    "Firewood": "206",
    "Fish": "366",
    "Flower Broom": "365",
    "Foxtail Millet(Navane)": "121",
    "French Beans (Frasbean)": "298",
    "Galgal(Lemon)": "350",
    "Garlic": "25",
    "Ghee": "249",
    "Gingelly Oil": "276",
    "Ginger(Dry)": "27",
    "Ginger(Green)": "103",
    "Gladiolus Bulb": "364",
    "Gladiolus Cut Flower": "363",
    "Goat": "219",
    "Goat Hair": "353",
    "Gram Raw(Chholia)": "359",
    "Gramflour": "294",
    "Grapes": "22",
    "Green Avare (W)": "165",
    "Green Chilli": "87",
    "Green Fodder": "346",
    "Green Gram (Moong)(Whole)": "9",
    "Green Gram Dal (Moong Dal)": "265",
    "Green Peas": "50",
    "Ground Nut Oil": "267",
    "Ground Nut Seed": "268",
    "Groundnut": "10",
    "Groundnut (Split)": "314",
    "Groundnut pods (raw)": "312",
    "Guar": "75",
    "Guar Seed(Cluster Beans Seed)": "413",
    "Guava": "185",
    "Gur(Jaggery)": "74",
    "Gurellu": "279",
    "Haralekai": "252",
    "He Buffalo": "216",
    "Hen": "369",
    "Hippe Seed": "125",
    "Honey": "236",
    "Honge seed": "124",
    "Hybrid Cumbu": "119",
    "Indian Beans (Seam)": "299",
    "Indian Colza(Sarson)": "344",
    "Isabgul (Psyllium)": "256",
    "Jack Fruit": "182",
    "Jaffri": "406",
    "Jaggery": "151",
    "Jamamkhan": "175",
    "Jamun(Narale Hannu)": "184",
    "Jarbara": "376",
    "Jasmine": "229",
    "Javi": "250",
    "Jowar(Sorghum)": "5",
    "Jute": "16",
    "Jute Seed": "210",
    "Kabuli Chana(Chickpeas-White)": "362",
    "Kacholam": "317",
    "Kakada": "230",
    "Kankambra": "233",
    "Karamani": "115",
    "Karbuja(Musk Melon)": "187",
    "Kartali (Kantola)": "305",
    "Kharif Mash": "61",
    "Khoya": "372",
    "Kinnow": "336",
    "Knool Khol": "177",
    "Kodo Millet(Varagu)": "117",
    "Kuchur": "243",
    "Kulthi(Horse Gram)": "114",
    "Ladies Finger": "155",
    "Lak(Teora)": "96",
    "Leafy Vegetable": "171",
    "Lemon": "310",
    "Lentil (Masur)(Whole)": "63",
    "Lilly": "378",
    "Lime": "180",
    "Linseed": "67",
    "Lint": "280",
    "Litchi": "351",
    "Little gourd (Kundru)": "302",
    "Long Melon(Kakri)": "304",
    "Lotus": "403",
    "Lotus Sticks": "339",
    "Lukad": "337",
    "Mace": "107",
    "Mahedi": "411",
    "Mahua": "335",
    "Mahua Seed(Hippe seed)": "371",
    "Maida Atta": "288",
    "Maize": "4",
    "Mango": "20",
    "Mango (Raw-Ripe)": "172",
    "Maragensu": "225",
    "Marasebu": "181",
    "Marget": "407",
    "Marigold(Calcutta)": "235",
    "Marigold(loose)": "405",
    "Mash": "60",
    "Mashrooms": "340",
    "Masur Dal": "259",
    "Mataki": "93",
    "Methi Seeds": "47",
    "Methi(Leaves)": "46",
    "Millets": "237",
    "Mint(Pudina)": "360",
    "Moath Dal": "258",
    "Moath Dal": "95",
    "Mousambi(Sweet Lime)": "77",
    "Mustard": "12",
    "Mustard Oil": "324",
    "Myrobolan(Harad)": "142",
    "Nargasi": "245",
    "Nearle Hannu": "222",
    "Neem Seed": "126",
    "Nelli Kai": "223",
    "Niger Seed (Ramtil)": "98",
    "Nutmeg": "106",
    "Onion": "23",
    "Onion Green": "358",
    "Orange": "18",
    "Orchid": "381",
    "Other Pulses": "97",
    "Ox": "213",
    "Paddy(Dhan)(Basmati)": "414",
    "Paddy(Dhan)(Common)": "2",
    "Papaya": "72",
    "Papaya (Raw)": "313",
    "Patti Calcutta": "404",
    "Peach": "331",
    "Pear(Marasebu)": "330",
    "Peas cod": "308",
    "Peas Wet": "174",
    "Peas(Dry)": "347",
    "Pegeon Pea (Arhar Fali)": "301",
    "Pepper garbled": "109",
    "Pepper ungarbled": "110",
    "Persimon(Japani Fal)": "327",
    "Pigs": "220",
    "Pineapple": "21",
    "Plum": "329",
    "Pointed gourd (Parval)": "303",
    "Polherb": "240",
    "Pomegranate": "190",
    "Potato": "24",
    "Pumpkin": "84",
    "Pundi": "254",
    "Pundi Seed": "128",
    "Raddish": "161",
    "Ragi (Finger Millet)": "30",
    "Raibel": "409",
    "Rajgir": "248",
    "Ram": "282",
    "Rat Tail Radish (Mogari)": "307",
    "Raya": "65",
    "Red Gram": "7",
    "Resinwood": "322",
    "Riccbcan": "62",
    "Rice": "3",
    "Ridge gourd(Tori)": "160",
    "Rose(Local)": "374",
    "Rose(Loose)": "228",
    "Rose(Tata)": "373",
    "Round gourd": "306",
    "Rubber": "111",
    "Sabu Dana": "291",
    "Safflower": "59",
    "Saffron": "338",
    "Sajje": "271",
    "Same/Savi": "122",
    "Sarasum": "247",
    "Season Leaves": "277",
    "Seegu": "253",
    "Seemebadnekai": "176",
    "Seetafal": "201",
    "Sesamum(Sesame,Gingelly,Til)": "11",
    "She Buffalo": "217",
    "She Goat": "283",
    "Sheep": "218",
    "Siddota": "183",
    "Skin And Hide": "226",
    "Snake gourd": "156",
    "Soanf": "135",
    "Soapnut(Antawala/Retha)": "207",
    "Soji": "286",
    "Sompu": "246",
    "Soyabean": "13",
    "Spinach": "342",
    "Sponge gourd": "311",
    "Squash(Chappal Kadoo)": "332",
    "Sugar": "48",
    "Sugarcane": "150",
    "Sunflower": "14",
    "Sunflower Seed": "285",
    "Sunhemp": "139",
    "Suram": "242",
    "Surat Beans (Papadi)": "300",
    "Suva (Dill Seed)": "255",
    "Suvarna Gadde": "178",
    "Sweet Potato": "152",
    "Sweet Pumpkin": "173",
    "T.V. Cumbu": "120",
    "Tamarind Fruit": "261",
    "Tamarind Seed": "208",
    "Tapioca": "100",
    "Taramira": "76",
    "Tea": "44",
    "Tender Coconut": "200",
    "Thinai (Italian Millet)": "116",
    "Thogrikai": "170",
    "Thondekai": "162",
    "Tinda": "349",
    "Tobacco": "141",
    "Tomato": "78",
    "Torchwood": "323",
    "Toria": "66",
    "Tube Flower": "234",
    "Tube Rose(Double)": "401",
    "Tube Rose(Loose)": "408",
    "Tube Rose(Single)": "377",
    "Turmeric": "39",
    "Turmeric (raw)": "309",
    "Turnip": "341",
    "Walnut": "343",
    "Water Melon": "73",
    "Wheat": "1",
    "Wheat Atta": "287",
    "White Peas": "412",
    "White Pumpkin": "158",
    "Wood": "203",
    "Wool": "348",
    "Yam": "244",
    "Yam (Ratalu)": "297"
}

module.exports.statesToCode = {
    "Andaman and Nicobar": "AN",
    "Andhra Pradesh": "AP",
    "Arunachal Pradesh": "AR",
    "Assam": "AS",
    "Bihar": "BI",
    "Chandigarh": "CH",
    "Chattisgarh": "CG",
    "Dadra and Nagar Haveli": "DN",
    "Daman and Diu": "DD",
    "Goa": "GO",
    "Gujarat": "GJ",
    "Haryana": "HR",
    "Himachal Pradesh": "HP",
    "Jammu and Kashmir": "JK",
    "Jharkhand": "JR",
    "Karnataka": "KK",
    "Kerala": "KL",
    "Lakshadweep": "LD",
    "Madhya Pradesh": "MP",
    "Maharashtra": "MH",
    "Manipur": "MN",
    "Meghalaya": "MG",
    "Mizoram": "MZ",
    "Nagaland": "NG",
    "NCT of Delhi": "DL",
    "Odisha": "OR",
    "Pondicherry": "PC",
    "Punjab": "PB",
    "Rajasthan": "RJ",
    "Sikkim": "SK",
    "Tamil Nadu": "TN",
    "Telangana": "TL",
    "Tripura": "TR",
    "Uttar Pradesh": "UP",
    "Uttrakhand": "UC",
    "West Bengal": "WB"
}

module.exports.months = {
    "Jan": () => 31,
    "Feb": (year) => year%4? 28: 29,
    "Mar": () => 31,
    "Apr": () => 30,
    "May": () => 31,
    "Jun": () => 30,
    "Jul": () => 31,
    "Aug": () => 31,
    "Sep": () => 30,
    "Oct": () => 31,
    "Nov": () => 30,
    "Dec": () => 31
}

function makeReverseMap(obj) {
    let output = {};
    for (let key of Object.keys(obj)) {
        let value = obj[key];
        output[value] = key;
    }
    return output;
}

module.exports.codeToStates = makeReverseMap(this.statesToCode);
module.exports.codeToCrops = makeReverseMap(this.cropsToCode);
